intel/SmartHome-Demo

dollhouse/ocf-servers/js-servers/README.md

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

Solar Panel: add Grove LCD panel to HW component list

---

first_server.js
ocf-servers/js-servers/ambient_light.js
ocf-servers/js-servers/button-toggle.js
ocf-servers/js-servers/button.js
ocf-servers/js-servers/buzzer.js
ocf-servers/js-servers/fan.js
ocf-servers/js-servers/gas.js
ocf-servers/js-servers/led.js
ocf-servers/js-servers/motion.js
ocf-servers/js-servers/power-uart.js
ocf-servers/js-servers/rgb_led.js
ocf-servers/js-servers/solar.js
ocf-servers/js-servers/switch.js
ocf-servers/js-servers/temperature.js
package.json

This branch contains the changes that are needed to run the demo based on iotivity-node v1.1.0 and latest JS API spec.

Upgrade demo to iotivity-node v1.1.0 and latest JS API spec

---

README.md

Signed-off-by: Ulf <ulf.hofemeier@linux.intel.com>

Update README recommending Ostro OS as preferred OS to build demo.

---

ocf-servers/soletta-js-servers/README.md
ocf-servers/soletta-js-servers/ambient_light.js
ocf-servers/soletta-js-servers/button-toggle.js
ocf-servers/soletta-js-servers/button.js
ocf-servers/soletta-js-servers/buzzer.js
ocf-servers/soletta-js-servers/fan.js
ocf-servers/soletta-js-servers/gas.js
ocf-servers/soletta-js-servers/led.js
ocf-servers/soletta-js-servers/motion.js
ocf-servers/soletta-js-servers/rgb_led.js
ocf-servers/soletta-js-servers/switch.js
ocf-servers/soletta-js-servers/temperature.js

This branch includes the implementation of GPIO and AIO based sensor servers using Soletta I/O Node.js bindings.

Implement sensor servers using Soletta I/O Node.js bindings

---

ocf-servers/js-servers/ambient_light.js
ocf-servers/js-servers/button-toggle.js
ocf-servers/js-servers/button.js
ocf-servers/js-servers/buzzer.js
ocf-servers/js-servers/fan.js
ocf-servers/js-servers/gas.js
ocf-servers/js-servers/led.js
ocf-servers/js-servers/motion.js
ocf-servers/js-servers/power-uart.js
ocf-servers/js-servers/rgb_led.js
ocf-servers/js-servers/solar.js
ocf-servers/js-servers/switch.js
ocf-servers/js-servers/temperature.js
ocf-servers/soletta-js-servers/ambient_light.js
ocf-servers/soletta-js-servers/button-toggle.js
ocf-servers/soletta-js-servers/button.js
ocf-servers/soletta-js-servers/buzzer.js
ocf-servers/soletta-js-servers/fan.js
ocf-servers/soletta-js-servers/gas.js
ocf-servers/soletta-js-servers/led.js
ocf-servers/soletta-js-servers/motion.js
ocf-servers/soletta-js-servers/rgb_led.js
ocf-servers/soletta-js-servers/switch.js
ocf-servers/soletta-js-servers/temperature.js
package.json

This removes suffix "Resource" from (un)?registerResource as per the spec.

Update OCF servers implementation to the latest JS spec

---

first_server.js
ocf-servers/js-servers/ambient_light.js
ocf-servers/js-servers/button-toggle.js
ocf-servers/js-servers/button.js
ocf-servers/js-servers/buzzer.js
ocf-servers/js-servers/fan.js
ocf-servers/js-servers/gas.js
ocf-servers/js-servers/led.js
ocf-servers/js-servers/motion.js
ocf-servers/js-servers/power-uart.js
ocf-servers/js-servers/rgb_led.js
ocf-servers/js-servers/solar.js
ocf-servers/js-servers/switch.js
ocf-servers/js-servers/temperature.js

This will disable the console logging by default, but users can enable
it by running the program with 'NODE_DEBUG=<module name>'.
Client: NODE_DEBUG=first_server node first_server.js
Sensor: NODE_DEBUG=fan node fan.js

Use debuglog to enable logging conditionally

---

first_server.js
ostro-config/systemd-services/first-server/dollhouse.service
package.json

Remove systemd module dependency by adding socket
activation support directly.

Remove systemd module dependency

---

ocf-servers/js-servers/ambient_light.js
ocf-servers/js-servers/button-toggle.js
ocf-servers/js-servers/button.js
ocf-servers/js-servers/buzzer.js
ocf-servers/js-servers/fan.js
ocf-servers/js-servers/gas.js
ocf-servers/js-servers/led.js
ocf-servers/js-servers/motion.js
ocf-servers/js-servers/power-uart.js
ocf-servers/js-servers/rgb_led.js
ocf-servers/js-servers/solar.js
ocf-servers/js-servers/switch.js
ocf-servers/js-servers/temperature.js
ocf-servers/soletta-js-servers/ambient_light.js
ocf-servers/soletta-js-servers/button-toggle.js
ocf-servers/soletta-js-servers/button.js
ocf-servers/soletta-js-servers/buzzer.js
ocf-servers/soletta-js-servers/fan.js
ocf-servers/soletta-js-servers/gas.js
ocf-servers/soletta-js-servers/led.js
ocf-servers/soletta-js-servers/motion.js
ocf-servers/soletta-js-servers/rgb_led.js
ocf-servers/soletta-js-servers/switch.js
ocf-servers/soletta-js-servers/temperature.js
package.json

Replace extend() with Object.assign() and remove
lodash module dependency.

Remove lodash module dependency

---

ocf-servers/js-servers/ambient_light.js
ocf-servers/js-servers/button-toggle.js
ocf-servers/js-servers/button.js
ocf-servers/js-servers/buzzer.js
ocf-servers/js-servers/fan.js
ocf-servers/js-servers/gas.js
ocf-servers/js-servers/led.js
ocf-servers/js-servers/motion.js
ocf-servers/js-servers/power-uart.js
ocf-servers/js-servers/rgb_led.js
ocf-servers/js-servers/solar.js
ocf-servers/js-servers/switch.js
ocf-servers/js-servers/temperature.js
ocf-servers/soletta-js-servers/ambient_light.js
ocf-servers/soletta-js-servers/button-toggle.js
ocf-servers/soletta-js-servers/button.js
ocf-servers/soletta-js-servers/buzzer.js
ocf-servers/soletta-js-servers/fan.js
ocf-servers/soletta-js-servers/gas.js
ocf-servers/soletta-js-servers/led.js
ocf-servers/soletta-js-servers/motion.js
ocf-servers/soletta-js-servers/rgb_led.js
ocf-servers/soletta-js-servers/switch.js
ocf-servers/soletta-js-servers/temperature.js

Fix the invalid date string format in the servers. Found this issue while testing the platform discovery API support https://github.com/01org/iot-rest-api-server/pull/28.

Fix the invalid date string format

---

ocf-servers/js-servers/ambient_light.js
ocf-servers/js-servers/button-toggle.js
ocf-servers/js-servers/button.js
ocf-servers/js-servers/buzzer.js
ocf-servers/js-servers/fan.js
ocf-servers/js-servers/gas.js
ocf-servers/js-servers/led.js
ocf-servers/js-servers/motion.js
ocf-servers/js-servers/power-uart.js
ocf-servers/js-servers/rgb_led.js
ocf-servers/js-servers/solar.js
ocf-servers/js-servers/switch.js
ocf-servers/js-servers/temperature.js
package.json

This updates the client and servers implementation to IoTivity 1.1.1.

Update client and servers implementation to IoTivity 1.1.1

---

sensors/DC_power_meter/README.md

Signed-off-by: Kien Dinh <kien.t.dinh@intel.com>

Added supported Zephyr versions

---

ocf-servers/js-servers/temperature.js
rules-engine/rules.json

This PR includes the following bug fixes.
- Handle undefined queryOptions in temperature retrieve handler.
- Update rules to set the RGB LED color to Blue by default

Fix bugs in temperature and sensor rules

---

smarthome-web-portal/tools/docker/web-portal.conf

The repo moved to 01org. So the process directory in the supervisor configuration file also needs change.

Update the project folder in the conf file for the new repo.

---

package.json

package.json: Update iotivity-node dependency to v1.1.1-3

---

smarthome-web-portal/tools/smarthome-admin-portal/README.md
smarthome-web-portal/tools/smarthome-admin-portal/requirements.txt

@gvancuts @ttzeng 
I have corrected the dependency list of the admin portal and improve the README.md.

Admin Portal: update the requirement.txt and README.md

---

package.json

Signed-off-by: Hongjuan Wang <hongjuan.wang@intel.com>

Move package.json from gateway to root folder

---

sensors/environmental-sensors/README.md

- Fix typos issue
- Add detail steps for setting up dev environment
- Add description that how to enable BLE on gateway
Signed-off-by: Hongjuan Wang <hongjuan.wang@intel.com>

documentation: improve environmental-sensors README.md

---

ocf-servers/js-servers/temperature.js

Updated to use external ADC for uses with MinnowBoard

Temperature sensor: Updated to use external ADC

---

ocf-servers/js-servers/gas.js

Updated to use external ADC for uses with MinnowBoard

Gas sensor: Updated to use external ADC

---

ocf-servers/js-servers/ambient_light.js

Updated to use external ADC for uses with MinnowBoard

Ambient light sensor: Updated to use external ADC

---

smarthome-web-portal/Dockerfile
smarthome-web-portal/initial_db.py
smarthome-web-portal/tools/docker/README.md
smarthome-web-portal/tools/docker/sources.list

1. Upgrade to Ubuntu version 16.04; 
2. Disable updating sources.list
You may want to verify it by the commands below:
$ sudo docker pull xshan1/smarthome-demo:sourceslist
$ sudo docker run -d -e proxy=<ip of the proxy> --name portal -p 3030:3000 -p 3031:4000 xshan1/smarthome-demo:sourceslist
Signed-off-by: Theresa <theresa.shan@intel.com>

Changes for Open Source PDT review.

---

gateway/package.json
ocf-servers/README.md
ocf-servers/js-servers/README.md
ocf-servers/js-servers/ambient_light.js
ocf-servers/js-servers/button-toggle.js
ocf-servers/js-servers/button.js
ocf-servers/js-servers/buzzer.js
ocf-servers/js-servers/config/json-to-cbor.js
ocf-servers/js-servers/config/security.boilerplate.json
ocf-servers/js-servers/environmental_sensor.js
ocf-servers/js-servers/fan.js
ocf-servers/js-servers/gas.js
ocf-servers/js-servers/led.js
ocf-servers/js-servers/motion.js
ocf-servers/js-servers/power-uart.js
ocf-servers/js-servers/rgb_led.js
ocf-servers/js-servers/solar.js
ocf-servers/js-servers/switch.js
ocf-servers/js-servers/temperature.js
ocf-servers/package.json
package.json

This commit updates all OCF servers to the latest JS spec and
iotivity v1.3.0. It also includes the scripts that are needed to 
create secure configurations.

Update OCF servers to the latest JS spec and iotivity v1.3.0

---

ocf-servers/js-servers/buzzer.js

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

buzzer.js: fix typo in the code (debuglog was misspelled)

---

ocf-servers/zjs-servers/multiserver.js
ocf-servers/zjs-servers/multiserver2.js

Signed-off-by: Zhang xiaoyu <xiaoyux.zhang@intel.com>
Type| Pass | Fail |Block | Comment 
---| ---| ---| ---|--- 
manual | 2 | 0 | 0 |

Remove arduino101_pins module and update led

---

ocf-servers/zjs-servers/multiserver_a101.js
ocf-servers/zjs-servers/multiserver_k64f.js
ocf-servers/zjs-servers/temperature.js

Signed-off-by: Zhang xiaoyu <xiaoyu3x.zhang@intel.com>
Type| Pass| Fail |Block | Comment
---| ---| ---| ---|--- 
manual | 3 | 0 | 0 |

Change 'onchange' to 'onreading' by new W3C Generic Sensor API
